version: "3"

services:
  app:
    image: cornellappdev/eatery-blue:${IMAGE_TAG}
    env_file: .env
    stdin_open: true # docker run -i
    tty: true # docker run -t
    command: sh -c "python manage.py migrate && printenv > /etc/environment && { cron -f & python manage.py runserver 0.0.0.0:8000; }"
    ports:
      - "8000:8000"
    restart: always
